(async () => {
  const { assert, send, wait, policy } = window.lab;
  const $ = id => document.getElementById(id);
  const root = document.scrollingElement;
  const panel = $('panel');
  const wheel = (target, init = {}) => {
    const event = new WheelEvent('wheel', { deltaY: 80, bubbles: true, cancelable: true, ...init });
    target.dispatchEvent(event); return event;
  };
  const key = (target, init = {}) => {
    const event = new KeyboardEvent('keydown', { key: 'PageDown', bubbles: true, cancelable: true, ...init });
    target.dispatchEvent(event); return event;
  };
  const origin = () => root.scrollTo({ top: 0, behavior: 'instant' });
  let clicks = 0;
  $('ordinary-button').addEventListener('click', () => { $('ordinary-count').textContent = `Button clicks: ${++clicks}`; });
  try {
    await wait(); origin();
    policy.settings = { motion: false, consentChoices: false, backgroundVideo: false, youtubeQuiet: false, youtubeRecommendations: false, pageMode: true, grayscale: { enabled: true, level: 65 } };
    await send({ type: 'QB_REFRESH' });
    assert(document.querySelectorAll('[data-qb-comfort]').length === 1, 'Exactly one navigation toolbar appears');
    assert(getComputedStyle(root).filter.includes('grayscale(0.65)'), '65% grayscale composes with the original root filter');
    assert(getComputedStyle(root).filter.includes('brightness(1)'), 'Existing page filter is retained');
    assert($('fixed-header').getBoundingClientRect().top === 0, 'Grayscale leaves a fixed header attached to the viewport');
    const expected = globalThis.QuietBrowseComfort.pageDistance(innerHeight, 56);
    const first = wheel($('intro'));
    assert(first.defaultPrevented && Math.abs(root.scrollTop - expected) <= 1, 'One wheel gesture jumps immediately, accounting for the fixed header and overlap');
    const top = root.scrollTop;
    wheel($('intro'), { deltaY: 40 }); wheel($('intro'), { deltaY: 10 });
    assert(root.scrollTop === top, 'Momentum events in the same gesture do not skip more screens');
    await wait(80);
    assert(root.scrollTop === top, 'The page does not animate after the jump');
    assert($('fixed-header').getBoundingClientRect().top === 0, 'The fixed header remains fixed after paging');
    await wait(330); wheel($('intro'));
    assert(root.scrollTop > top, 'A fresh gesture advances another screen');
    const beforeUp = root.scrollTop; key(document.body, { key: 'PageUp' });
    assert(root.scrollTop < beforeUp, 'Page Up moves one screen immediately');
    const afterUp = root.scrollTop; key(document.body, { key: 'PageUp', repeat: true });
    assert(root.scrollTop === afterUp, 'Holding a paging key does not race through screens');
    origin(); await wait(330);
    panel.scrollTo({ top: 0, behavior: 'instant' });
    wheel($('panel-content'));
    assert(panel.scrollTop > 150 && panel.scrollTop <= panel.clientHeight - 32 && root.scrollTop === 0, 'Nested panels page locally, accounting for their sticky heading');
    const panelTop = panel.scrollTop; key(document.body);
    assert(panel.scrollTop > panelTop && root.scrollTop === 0, 'Keyboard paging remembers the selected panel');
    panel.scrollTo({ top: panel.scrollHeight, behavior: 'instant' }); await wait(330);
    wheel($('panel-content'));
    assert(root.scrollTop === 0, 'A contained panel does not spill paging into the document at its end');
    assert(!wheel($('intro'), { ctrlKey: true }).defaultPrevented, 'Ctrl-wheel zoom is not intercepted');
    assert(!wheel($('intro'), { altKey: true }).defaultPrevented, 'Alt-wheel bypass preserves normal scrolling');
    assert(!wheel($('intro'), { deltaX: 100, deltaY: 10 }).defaultPrevented, 'Horizontal wheel gestures are not intercepted');
    assert(!wheel($('memo')).defaultPrevented && !key($('memo')).defaultPrevented, 'Text fields retain their native wheel and keyboard behavior');
    assert(!key($('ordinary-button'), { key: ' ' }).defaultPrevented, 'Buttons retain native Space behavior');
    $('ordinary-button').click();
    assert(clicks === 1, 'Original button handlers still run');
    const beforePause = root.scrollTop;
    await send({ type: 'QB_PAUSE', paused: true });
    assert(!document.querySelector('[data-qb-comfort],[data-qb-page-target]') && !root.hasAttribute('data-qb-paging'), 'Show original removes toolbar and paging markers');
    assert(getComputedStyle(root).filter === 'brightness(1)' && root.style.filter === '', 'Show original restores the original filter immediately');
    assert(getComputedStyle(root).scrollBehavior === 'smooth', 'Show original restores the site’s own scroll behavior');
    assert(root.scrollTop === beforePause && $('memo').value === 'Keep this note.', 'Undo preserves scroll position and unfinished input');
    assert(!wheel($('intro')).defaultPrevented, 'No wheel interception remains after pausing');

    // Exercise the same production controller with a deterministic local clock.
    const controller = globalThis.QuietBrowsePageComfort.create();
    controller.start({ grayscale: { enabled: true, scheduled: true, windows: [{ days: [1], start: '21:00', end: '07:00', level: 100 }] } });
    controller.tick(new Date(2026, 7, 24, 21));
    assert(getComputedStyle(root).filter.includes('grayscale(1)'), 'A scheduled start applies its configured amount');
    controller.tick(new Date(2026, 7, 25, 6, 59));
    assert(controller.status().grayscale === 100, 'An overnight window continues into the following morning');
    controller.tick(new Date(2026, 7, 25, 7));
    assert(getComputedStyle(root).filter === 'brightness(1)', 'The end boundary returns the site to color without a fade');
    controller.start({ grayscale: { enabled: true, level: 0 } });
    assert(root.style.filter === '', 'Zero percent makes no filter modification');
    controller.start({ pageMode: true }); origin();
    root.classList.add('root-locked');
    assert(!wheel($('intro')).defaultPrevented, 'A site’s locked document is not forcibly scrolled');
    panel.scrollTo({ top: 0, behavior: 'instant' }); await wait(330); wheel($('panel-content'));
    assert(panel.scrollTop > 0 && root.scrollTop === 0, 'A panel remains pageable while its outer document is locked');
    const parent = panel.parentNode, next = panel.nextSibling;
    panel.remove(); controller.sync();
    assert(!panel.hasAttribute('data-qb-page-target'), 'Detached panels release their paging modifications');
    parent.insertBefore(panel, next);
    controller.stop(); root.classList.remove('root-locked');
    assert(!document.querySelector('[data-qb-comfort]'), 'Stopping the controller removes its interface and listeners');
    await send({ type: 'QB_PAUSE', paused: false });
    const firstToolbar = document.querySelector('[data-qb-comfort]');
    await send({ type: 'QB_CLOCK' });
    assert(document.querySelector('[data-qb-comfort]') === firstToolbar, 'Clock updates do not rebuild or reset the paging toolbar');
    origin(); panel.scrollTo({ top: 0, behavior: 'instant' });
    document.body.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
    const bar = firstToolbar.shadowRoot;
    bar.querySelector('[aria-label="Next screen"]').click();
    assert(Math.abs(root.scrollTop - expected) <= 1, 'The Next screen button advances the document immediately');
    bar.querySelector('[aria-label="Previous screen"]').click();
    assert(root.scrollTop === 0, 'The Previous screen button returns immediately');
    bar.querySelector('[aria-label="Use normal scrolling for this page"]').click();
    assert(!root.hasAttribute('data-qb-paging') && !wheel($('intro')).defaultPrevented, 'Normal scroll releases wheel navigation without turning off grayscale');
    await send({ type: 'QB_CLOCK' });
    assert(!root.hasAttribute('data-qb-paging') && getComputedStyle(root).filter.includes('grayscale(0.65)'), 'Clock ticks preserve a temporary normal-scroll choice');
    bar.querySelector('[aria-label="Resume instant page navigation"]').click();
    assert(root.getAttribute('data-qb-paging') === 'on', 'Resume pages restores the arrows without reloading');
    const total = document.querySelectorAll('#results li.pass').length;
    $('test-status').textContent = `PASS — ${total} paging/grayscale DOM checks. Chrome APIs simulated. Try the arrows below.`;
  } catch (error) { $('test-status').textContent = `FAIL — ${error.message}`; console.error(error); }
})();
